name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  COLUMNS: "120"
  FORCE_COLOR: "1"
  PYTHONUNBUFFERED: "1"

jobs:
  test:
    name: Test ${{ matrix.py }} - django${{ matrix.django }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { py: "3.14", django: "52" }
          - { py: "3.13", django: "52" }
          - { py: "3.13", django: "51" }
          - { py: "3.12", django: "52" }
          - { py: "3.12", django: "51" }
          - { py: "3.12", django: "50" }
          - { py: "3.12", django: "42" }
          - { py: "3.11", django: "52" }
          - { py: "3.11", django: "51" }
          - { py: "3.11", django: "50" }
          - { py: "3.11", django: "42" }
          - { py: "3.11", django: "41" }
          - { py: "3.10", django: "52" }
          - { py: "3.10", django: "51" }
          - { py: "3.10", django: "50" }
          - { py: "3.10", django: "42" }
          - { py: "3.10", django: "41" }
    steps:
      - uses: actions/checkout@v5
      - name: Setup python for tox
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - run: python -m pip install tox
      - uses: actions/checkout@v5
      - run: env
      - name: Setup python for test ${{ matrix.py }} - django${{ matrix.django }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.py }}
      - name: Setup test suite
        run: tox -e py${{ matrix.py }}-django${{ matrix.django }} -vv --notest
      - name: Run test suite
        run: tox -e py${{ matrix.py }}-django${{ matrix.django }} --skip-pkg-install
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
          name: codecov-py${{ matrix.py }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  static-typing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - run: python -m pip install tox
      - name: Run mypy
        run: tox -e mypy

  lint:
    name: Lint
    uses: less-action/reusables/.github/workflows/pre-commit.yaml@main
    with:
      python-version: "3.12"

  check-build:
    name: Check packaging
    uses: less-action/reusables/.github/workflows/python-test-build.yaml@main
